name: "Build, check, test, release"
on:
  push:
    branches:
      - 'agave-v2.0'
  pull_request:

jobs:
  test:
    name: cargo check + test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.76.0

      - name: Install protobuf
        run: sudo apt-get install protobuf-compiler

      - name: Clone protosol
        run: ./scripts/fetch_proto.sh

      - name: Check lints and clippy
        run: |
          rustup component add rustfmt
          rustup component add clippy
          cargo fmt --all -- --check
          cargo clippy --all

      - name: Test
        run: |
          cargo check
          cargo test

      - name: Run build
        run: make build

      - name: Run test-vectors
        run: |
          cargo build --release
          ./scripts/run_test_vectors.sh

      - uses: actions/upload-artifact@v4
        with:
          name: libsolfuzz-agave.so
          path: ./target/x86_64-unknown-linux-gnu/release/libsolfuzz_agave.so
